# Generated by Django 6.0.6 on 2026-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='--', max_length=255),
            preserve_default=False,
        ),
    ]
