# Generated by Django 6.0.6 on 2026-07-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_membership_alter_order_payment_status'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title) VALUES('collection1')
        """, """
        DELETE FROM store_collection WHERE title='collection1'
        """)
    ]
