# Generated by Django 6.0.7 on 2026-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_city_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Petora BD', max_length=255)),
                ('support_email', models.EmailField(default='support@petorabd.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('delivery_charge_inside', models.DecimalField(decimal_places=2, default=60.0, max_digits=6)),
                ('delivery_charge_outside', models.DecimalField(decimal_places=2, default=120.0, max_digits=6)),
            ],
        ),
    ]
