# Generated by Django 6.0.7 on 2026-08-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_method_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for the card view', max_length=500)),
                ('content', models.TextField(help_text='Full HTML or Markdown content')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Scheduled', 'Scheduled')], default='Draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.ManyToManyField(blank=True, related_name='featured_in_articles', to='store.product')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='store.articlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
