# Generated by Django 6.0.7 on 2026-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_articlecategory_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Store Setting', 'verbose_name_plural': 'Store Settings'},
        ),
        migrations.AddField(
            model_name='storesettings',
            name='business_hours',
            field=models.CharField(blank=True, default='9:00 AM - 10:00 PM (Everyday)', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='short_description',
            field=models.TextField(blank=True, default='Your trusted partner for premium pet care, food, and accessories.', help_text='লোগোর নিচে দেখানোর জন্য শর্ট টেক্সট'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube Channel URL'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='কাস্টমার কেয়ার বা হটলাইন নম্বর', max_length=20),
        ),
    ]
