# Generated by Django 6.0.7 on 2026-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_storesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency_symbol',
            field=models.CharField(default='৳', help_text='Ex: $, ৳, €, £', max_length=5),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='hotline number', max_length=20),
        ),
    ]
