# Generated by Django 6.0.7 on 2026-09-02 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PETORA20, WINTER50', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum cart value required', max_digits=8)),
                ('is_global', models.BooleanField(default=True, help_text='If True, applies to all products.')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used globally', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('applicable_collections', models.ManyToManyField(blank=True, related_name='coupons', to='store.collection')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='store.product')),
            ],
            options={
                'ordering': ['-valid_to'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon'),
        ),
    ]
