# Generated by Django 6.0.7 on 2026-09-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_discount_amount_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g. 8801xxxxxxxxx (without +)', max_length=20, null=True),
        ),
    ]
