# Generated by Django 6.0.7 on 2026-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='messenger_link',
            field=models.URLField(blank=True, help_text='e.g. https://m.me/yourpage', null=True),
        ),
    ]
