# Generated by Django 6.0.7 on 2026-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storesettings_messenger_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='e.g. 123456789012345', max_length=50, null=True),
        ),
    ]
