# Generated by Django 6.0.7 on 2026-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gtm_id',
            field=models.CharField(blank=True, help_text='e.g. GTM-XXXXXXX', max_length=50, null=True),
        ),
    ]
